name: Deploy via rsync

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_FOLDER: /home/username/public_html/ # Deploy directory on the production server

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - shell: bash
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create Release Dir On Remote
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'mkdir -p ${{ env.DEPLOY_FOLDER }}deploy/${{ github.sha }}'

      - name: Push files to the remote
        run: rsync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' --exclude-from=.rsyncignore ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.DEPLOY_FOLDER }}deploy/${{ github.sha }}

      - name: Ensure shared symlinks
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'mkdir -p ${{ env.DEPLOY_FOLDER }}private/shared/uploads && ln -sfn ${{ env.DEPLOY_FOLDER }}private/shared/uploads ${{ env.DEPLOY_FOLDER }}deploy/${{ github.sha }}/wp-content/uploads'

#      - name: Share wp-config file
#        run: |
#          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'touch ${{ env.DEPLOY_FOLDER }}private/shared/wp-config.php && ln -sfn ${{ env.DEPLOY_FOLDER }}private/shared/wp-config.php ${{ env.DEPLOY_FOLDER }}deploy/${{ github.sha }}/wp-config.php'

      - name: Promote production symlink
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} 'ln -sfn ${{ env.DEPLOY_FOLDER }}deploy/${{ github.sha }} ${{ env.DEPLOY_FOLDER }}public'